name: Daily Data Fetch and Hugo Build

on:
  workflow_dispatch: # 允许手动触发, 以便测试
  schedule:
    - cron: '0 22 * * *' # 每天 UTC 22 点执行

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v4
        with:
          # 获取所有历史记录, 以便 Hugo 和 git 操作能正确运行
          fetch-depth: 0 
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies and Run Scripts
        run: |
          pip install -r blogdata/requirements.txt
          python blogdata/run_all_daily.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # 如果 auto_push_github.py 需要, 请取消下面的注释
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Build and Deploy (Handled by auto_push_github.py)
        run: |
          echo "Build and Deploy steps are assumed to be handled by the auto_push_github.py script."
          echo "If not, you can add your git commands and hugo build here."