name: Daily Data Fetch and Hugo Build

on:
  workflow_dispatch: # 允许手动触发, 以便测试
  schedule:
    - cron: '0 22 * * *' # 每天 UTC 22 点执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 我们需要获取所有历史记录以便 Hugo 生成正确的 lastmod
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # 指定一个Python版本

      - name: Run python script
        working-directory: ./scraper_tool
        run: |
          pip install -r requirements.txt
          python run_all_daily.py
        env:
          HUGO_PROJECT_PATH: ${{ github.workspace }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # ... 其他环境变量

      - name: Debug Generated Summary File
        run: |
          echo "--- Checking summary file status ---"
          SUMMARY_FILE="${{ github.workspace }}/spiders/ai_news/summarized_articles.jsonl"
          if [ -f "$SUMMARY_FILE" ]; then
            echo "File exists. Listing details:"
            ls -l "$SUMMARY_FILE"
            echo "--- Checking summary file content (first 10 lines) ---"
            head -n 10 "$SUMMARY_FILE"
          else
            echo "!!! ERROR: Summary file does not exist at $SUMMARY_FILE !!!"
            ls -lR ${{ github.workspace }}
          fi
          echo "--- End of debug ---"

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # ... 其他部署选项