name: Daily Run All

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点执行
  workflow_dispatch:     # 允许手动触发

jobs:
  run-daily:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
      SEATABLE_API_TOKEN: ${{ secrets.SEATABLE_API_TOKEN }}
      SEATABLE_SERVER_URL: ${{ secrets.SEATABLE_SERVER_URL }}
      # 如有其他环境变量，继续添加

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run all daily scripts
        run: python run_all_daily.py
