name: Daily Data Fetch and Hugo Build

on:
  workflow_dispatch: # 允许手动触发, 以便测试
  schedule:
    - cron: '0 22 * * *' # 每天 UTC 22 点执行

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and run scripts
        run: |
          pip install -r blogdata/requirements.txt
          python blogdata/run_all_daily.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # 其他您需要的 secrets, 比如 auto_push_github.py 可能需要的 GITHUB_TOKEN 等
          # GH_PAT: ${{ secrets.GH_PAT }}
          
      - name: Build and Deploy (Optional - if auto_push is disabled)
        # 如果您的 auto_push_github.py 已经处理了构建和推送,
        # 那么下面的步骤可能就不需要了, 或者需要相应调整。
        # 这里保留一个基本的 Hugo 构建和部署的例子。
        run: |
          echo "Skipping direct build and deploy as it should be handled by python scripts."
          # git config --global user.name "github-actions[bot]"
          # git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # hugo
          # ./deploy.sh # or your deployment command